version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80

  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    networks:
      external:
        - host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://sd_consul:8500

networks:
  default:
    external:
      name: bridge
